//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCCleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Event Logs .
        /// </summary>
        internal static string AdvancedFeature_1 {
            get {
                return ResourceManager.GetString("AdvancedFeature_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Files Folder Path.
        /// </summary>
        internal static string AdvancedFeature_10 {
            get {
                return ResourceManager.GetString("AdvancedFeature_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Free Space .
        /// </summary>
        internal static string AdvancedFeature_11 {
            get {
                return ResourceManager.GetString("AdvancedFeature_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Prefetched Data .
        /// </summary>
        internal static string AdvancedFeature_2 {
            get {
                return ResourceManager.GetString("AdvancedFeature_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Order Cache.
        /// </summary>
        internal static string AdvancedFeature_3 {
            get {
                return ResourceManager.GetString("AdvancedFeature_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray Notification Cache.
        /// </summary>
        internal static string AdvancedFeature_4 {
            get {
                return ResourceManager.GetString("AdvancedFeature_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Size/Location Cache.
        /// </summary>
        internal static string AdvancedFeature_5 {
            get {
                return ResourceManager.GetString("AdvancedFeature_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Path.
        /// </summary>
        internal static string AdvancedFeature_6 {
            get {
                return ResourceManager.GetString("AdvancedFeature_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Assist History.
        /// </summary>
        internal static string AdvancedFeature_7 {
            get {
                return ResourceManager.GetString("AdvancedFeature_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Log Files.
        /// </summary>
        internal static string AdvancedFeature_8 {
            get {
                return ResourceManager.GetString("AdvancedFeature_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Windows Installation.
        /// </summary>
        internal static string AdvancedFeature_9 {
            get {
                return ResourceManager.GetString("AdvancedFeature_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Applications {
            get {
                object obj = ResourceManager.GetObject("Applications", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Reader.
        /// </summary>
        internal static string Applications_1 {
            get {
                return ResourceManager.GetString("Applications_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to McAfee Antivirus.
        /// </summary>
        internal static string Applications_2 {
            get {
                return ResourceManager.GetString("Applications_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Office Picture Manager.
        /// </summary>
        internal static string Applications_3 {
            get {
                return ResourceManager.GetString("Applications_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notepad++.
        /// </summary>
        internal static string Applications_4 {
            get {
                return ResourceManager.GetString("Applications_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Office.
        /// </summary>
        internal static string Applications_5 {
            get {
                return ResourceManager.GetString("Applications_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Cache.
        /// </summary>
        internal static string BrowserFeature_1 {
            get {
                return ResourceManager.GetString("BrowserFeature_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet History.
        /// </summary>
        internal static string BrowserFeature_2 {
            get {
                return ResourceManager.GetString("BrowserFeature_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        internal static string BrowserFeature_3 {
            get {
                return ResourceManager.GetString("BrowserFeature_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download History.
        /// </summary>
        internal static string BrowserFeature_4 {
            get {
                return ResourceManager.GetString("BrowserFeature_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Download Location.
        /// </summary>
        internal static string BrowserFeature_5 {
            get {
                return ResourceManager.GetString("BrowserFeature_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string BrowserFeature_6 {
            get {
                return ResourceManager.GetString("BrowserFeature_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Form Information.
        /// </summary>
        internal static string BrowserFeature_7 {
            get {
                return ResourceManager.GetString("BrowserFeature_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Passwords.
        /// </summary>
        internal static string BrowserFeature_8 {
            get {
                return ResourceManager.GetString("BrowserFeature_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact Databases.
        /// </summary>
        internal static string BrowserFeature_9 {
            get {
                return ResourceManager.GetString("BrowserFeature_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brush {
            get {
                object obj = ResourceManager.GetObject("Brush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Chrome {
            get {
                object obj = ResourceManager.GetObject("Chrome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edge {
            get {
                object obj = ResourceManager.GetObject("Edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Explorer {
            get {
                object obj = ResourceManager.GetObject("Explorer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Documents.
        /// </summary>
        internal static string ExplorerFeature_1 {
            get {
                return ResourceManager.GetString("ExplorerFeature_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run (in Start Menu).
        /// </summary>
        internal static string ExplorerFeature_2 {
            get {
                return ResourceManager.GetString("ExplorerFeature_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Explorer MRUs.
        /// </summary>
        internal static string ExplorerFeature_3 {
            get {
                return ResourceManager.GetString("ExplorerFeature_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Cache.
        /// </summary>
        internal static string ExplorerFeature_4 {
            get {
                return ResourceManager.GetString("ExplorerFeature_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskbar Jump List.
        /// </summary>
        internal static string ExplorerFeature_5 {
            get {
                return ResourceManager.GetString("ExplorerFeature_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Passwords.
        /// </summary>
        internal static string ExplorerFeature_6 {
            get {
                return ResourceManager.GetString("ExplorerFeature_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Firefox {
            get {
                object obj = ResourceManager.GetObject("Firefox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IE {
            get {
                object obj = ResourceManager.GetObject("IE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Internet {
            get {
                object obj = ResourceManager.GetObject("Internet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        internal static string Internet_1 {
            get {
                return ResourceManager.GetString("Internet_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uTorrent.
        /// </summary>
        internal static string Internet_2 {
            get {
                return ResourceManager.GetString("Internet_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Multimedia {
            get {
                object obj = ResourceManager.GetObject("Multimedia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Flash Player.
        /// </summary>
        internal static string Multimedia_1 {
            get {
                return ResourceManager.GetString("Multimedia_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Silverlight.
        /// </summary>
        internal static string Multimedia_2 {
            get {
                return ResourceManager.GetString("Multimedia_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Media Player.
        /// </summary>
        internal static string Multimedia_3 {
            get {
                return ResourceManager.GetString("Multimedia_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Registry {
            get {
                object obj = ResourceManager.GetObject("Registry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Registry_Left {
            get {
                object obj = ResourceManager.GetObject("Registry_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Shared Dlls.
        /// </summary>
        internal static string RegistryOptions_1 {
            get {
                return ResourceManager.GetString("RegistryOptions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete Software.
        /// </summary>
        internal static string RegistryOptions_10 {
            get {
                return ResourceManager.GetString("RegistryOptions_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at Startup.
        /// </summary>
        internal static string RegistryOptions_11 {
            get {
                return ResourceManager.GetString("RegistryOptions_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Menu Ordering.
        /// </summary>
        internal static string RegistryOptions_12 {
            get {
                return ResourceManager.GetString("RegistryOptions_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUI Cache.
        /// </summary>
        internal static string RegistryOptions_13 {
            get {
                return ResourceManager.GetString("RegistryOptions_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Events.
        /// </summary>
        internal static string RegistryOptions_14 {
            get {
                return ResourceManager.GetString("RegistryOptions_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Services.
        /// </summary>
        internal static string RegistryOptions_15 {
            get {
                return ResourceManager.GetString("RegistryOptions_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused File Extensions.
        /// </summary>
        internal static string RegistryOptions_2 {
            get {
                return ResourceManager.GetString("RegistryOptions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveX and Class Issues.
        /// </summary>
        internal static string RegistryOptions_3 {
            get {
                return ResourceManager.GetString("RegistryOptions_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Libraries.
        /// </summary>
        internal static string RegistryOptions_4 {
            get {
                return ResourceManager.GetString("RegistryOptions_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string RegistryOptions_5 {
            get {
                return ResourceManager.GetString("RegistryOptions_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts .
        /// </summary>
        internal static string RegistryOptions_6 {
            get {
                return ResourceManager.GetString("RegistryOptions_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Paths.
        /// </summary>
        internal static string RegistryOptions_7 {
            get {
                return ResourceManager.GetString("RegistryOptions_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Files.
        /// </summary>
        internal static string RegistryOptions_8 {
            get {
                return ResourceManager.GetString("RegistryOptions_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer.
        /// </summary>
        internal static string RegistryOptions_9 {
            get {
                return ResourceManager.GetString("RegistryOptions_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge.
        /// </summary>
        internal static string SearchArea_0 {
            get {
                return ResourceManager.GetString("SearchArea_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE.
        /// </summary>
        internal static string SearchArea_1 {
            get {
                return ResourceManager.GetString("SearchArea_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia.
        /// </summary>
        internal static string SearchArea_10 {
            get {
                return ResourceManager.GetString("SearchArea_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        internal static string SearchArea_11 {
            get {
                return ResourceManager.GetString("SearchArea_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string SearchArea_12 {
            get {
                return ResourceManager.GetString("SearchArea_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome.
        /// </summary>
        internal static string SearchArea_2 {
            get {
                return ResourceManager.GetString("SearchArea_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox.
        /// </summary>
        internal static string SearchArea_3 {
            get {
                return ResourceManager.GetString("SearchArea_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Explorer.
        /// </summary>
        internal static string SearchArea_4 {
            get {
                return ResourceManager.GetString("SearchArea_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SearchArea_5 {
            get {
                return ResourceManager.GetString("SearchArea_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string SearchArea_6 {
            get {
                return ResourceManager.GetString("SearchArea_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Store.
        /// </summary>
        internal static string SearchArea_7 {
            get {
                return ResourceManager.GetString("SearchArea_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string SearchArea_8 {
            get {
                return ResourceManager.GetString("SearchArea_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string SearchArea_9 {
            get {
                return ResourceManager.GetString("SearchArea_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap System {
            get {
                object obj = ResourceManager.GetObject("System", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Recycle Bin.
        /// </summary>
        internal static string SystemFeature_1 {
            get {
                return ResourceManager.GetString("SystemFeature_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Menu Shortcuts.
        /// </summary>
        internal static string SystemFeature_10 {
            get {
                return ResourceManager.GetString("SystemFeature_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Shortcuts .
        /// </summary>
        internal static string SystemFeature_11 {
            get {
                return ResourceManager.GetString("SystemFeature_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Files.
        /// </summary>
        internal static string SystemFeature_2 {
            get {
                return ResourceManager.GetString("SystemFeature_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string SystemFeature_3 {
            get {
                return ResourceManager.GetString("SystemFeature_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Dumps.
        /// </summary>
        internal static string SystemFeature_4 {
            get {
                return ResourceManager.GetString("SystemFeature_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chkdsk File Fragments.
        /// </summary>
        internal static string SystemFeature_5 {
            get {
                return ResourceManager.GetString("SystemFeature_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Log Files.
        /// </summary>
        internal static string SystemFeature_6 {
            get {
                return ResourceManager.GetString("SystemFeature_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Error Reporting.
        /// </summary>
        internal static string SystemFeature_7 {
            get {
                return ResourceManager.GetString("SystemFeature_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Cache .
        /// </summary>
        internal static string SystemFeature_8 {
            get {
                return ResourceManager.GetString("SystemFeature_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Cache.
        /// </summary>
        internal static string SystemFeature_9 {
            get {
                return ResourceManager.GetString("SystemFeature_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tick {
            get {
                object obj = ResourceManager.GetObject("Tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tools {
            get {
                object obj = ResourceManager.GetObject("Tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Utilities {
            get {
                object obj = ResourceManager.GetObject("Utilities", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-zip.
        /// </summary>
        internal static string Utilities_1 {
            get {
                return ResourceManager.GetString("Utilities_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teamviewer.
        /// </summary>
        internal static string Utilities_2 {
            get {
                return ResourceManager.GetString("Utilities_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Defender.
        /// </summary>
        internal static string Utilities_3 {
            get {
                return ResourceManager.GetString("Utilities_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Windows {
            get {
                object obj = ResourceManager.GetObject("Windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Explorer.
        /// </summary>
        internal static string Windows_1 {
            get {
                return ResourceManager.GetString("Windows_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Management Console.
        /// </summary>
        internal static string Windows_2 {
            get {
                return ResourceManager.GetString("Windows_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Paint.
        /// </summary>
        internal static string Windows_3 {
            get {
                return ResourceManager.GetString("Windows_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Search.
        /// </summary>
        internal static string Windows_4 {
            get {
                return ResourceManager.GetString("Windows_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEdit.
        /// </summary>
        internal static string Windows_5 {
            get {
                return ResourceManager.GetString("Windows_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop.
        /// </summary>
        internal static string Windows_6 {
            get {
                return ResourceManager.GetString("Windows_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowsStore {
            get {
                object obj = ResourceManager.GetObject("WindowsStore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing News.
        /// </summary>
        internal static string WindowStore_1 {
            get {
                return ResourceManager.GetString("WindowStore_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype Metro News.
        /// </summary>
        internal static string WindowStore_2 {
            get {
                return ResourceManager.GetString("WindowStore_2", resourceCulture);
            }
        }
    }
}
